name: Build and Zip Dist Folder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Zip dist folder
        run: zip -r global-suplementos-dist.zip dist/
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: global-suplementos-dist
          path: global-suplementos-dist.zip
